### ISSUE TITLE
做了个长按喷射的效果，时间久了报下面的异常

### ISSUE THREAD

**Issue by inteye** [Qiu800820/SuperLike#4]
思路：按下后在线程里循环喷射，抬起停止。按着不动时容易出现以下异常。连续点击还未出现。

java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.next(ArrayList.java:860)
        at com.sum.slike.SuperLikeLayout.draw(SuperLikeLayout.java:74)
        at android.view.View.updateDisplayListIfDirty(View.java:18510)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4313)
        at android.view.View.updateDisplayListIfDirty(View.java:18465)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4313)
        at android.view.View.updateDisplayListIfDirty(View.java:18465)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4313)
        at android.view.View.updateDisplayListIfDirty(View.java:18465)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4313)
        at android.view.View.updateDisplayListIfDirty(View.java:18465)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4313)
        at android.view.View.updateDisplayListIfDirty(View.java:18465)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4313)
        at android.view.View.updateDisplayListIfDirty(View.java:18465)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:846)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:852)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:999)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3410)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3206)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2755)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1737)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7795)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:975)
        at android.view.Choreographer.doCallbacks(Choreographer.java:781)
        at android.view.Choreographer.doFrame(Choreographer.java:716)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:961)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6900)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:820)

**Comment by Qiu800820** [comment]
因为ListArray不是线程安全的，也没在View上加锁。感觉没必要为少数多线程使用的情况去加锁
